#====================================================================
# Konfigurasi Netlify untuk Situs VuePress Profesional
#====================================================================

# Pengaturan build global yang diterapkan ke semua konteks deployment.
[build]
  # Perintah untuk membangun situs. Ini harus cocok dengan skrip di package.json.
  command = "npm run docs:build"

  # Direktori output dari perintah build, relatif terhadap basis.
  # Untuk VuePress, ini adalah direktori output standar.
  publish = "docs/.vuepress/dist"

  # Direktori tempat Netlify akan mencari fungsi serverless.
  functions = "netlify/functions"

# Variabel lingkungan yang diterapkan ke semua konteks build.
# Merupakan praktik terbaik untuk mengunci versi Node.js Anda.
# Ini juga dapat dilakukan dengan file .nvmrc, yang sering kali lebih disukai.
[build.environment]
  NODE_VERSION = "20"

#====================================================================
# Konteks Deployment: Sesuaikan build untuk lingkungan yang berbeda.
#====================================================================

# Konteks produksi (cabang utama Anda, mis., 'main' atau 'master')
[context.production]
  # Build produksi adalah standar. Tidak ada penimpaan yang diperlukan untuk situs sederhana.

# Konteks Deploy Preview (untuk Pull/Merge Request)
[context.deploy-preview]
  # Anda dapat menggunakan perintah yang berbeda untuk pratinjau, mis., untuk membangun draf.
  # command = "npm run docs:build"

#====================================================================
# Perutean dan Header
#====================================================================

# Aturan pengalihan untuk perutean Aplikasi Halaman Tunggal (SPA).
# Ini memastikan bahwa navigasi langsung ke sub-halaman berfungsi dengan benar saat di-refresh.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Header kustom untuk keamanan dan kinerja.
[[headers]]
  for = "/*"
  [headers.values]
    # Kebijakan Keamanan Konten yang DITINGKATKAN untuk VuePress Profesional
    # Setiap direktif dipisahkan oleh spasi, dan setiap kebijakan diakhiri dengan titik koma.
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://news.google.com giscus.app; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://news.google.com; img-src 'self' data: https://www.google-analytics.com https://www.googletagmanager.com https://avatars.githubusercontent.com; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https://www.google-analytics.com https://www.google-analytics.com/g/collect https://news.google.com; frame-src 'self' giscus.app; frame-ancestors 'none'; form-action 'self'; base-uri 'self'; object-src 'none';"
    
    # Mencegah situs dirender dalam iframe.
    X-Frame-Options = "DENY"
    
    # Mengaktifkan perlindungan XSS bawaan browser.
    X-XSS-Protection = "1; mode=block"
    
    # Mencegah browser menebak tipe konten.
    X-Content-Type-Options = "nosniff"