#.github/workflows/lighthouse.yml
name: Lighthouse CI
on: [push]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build VuePress site
        run: npm run docs:build
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.10.x
          lhci autorun